/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    2: typeof import('./.vitepress/theme/components/feishu/ArticleList copy 2.vue')['default']
    ACard: (typeof import("@arco-design/web-vue"))["Card"]
    ACol: (typeof import("@arco-design/web-vue"))["Col"]
    AIWebSites: typeof import('./.vitepress/theme/components/aiweb/AIWebSites.vue')['default']
    AList: (typeof import("@arco-design/web-vue"))["List"]
    AListItem: (typeof import("@arco-design/web-vue"))["ListItem"]
    Archive: typeof import('./.vitepress/theme/components/Archive.vue')['default']
    'Archive copy': typeof import('./.vitepress/theme/components/Archive copy.vue')['default']
    ARow: (typeof import("@arco-design/web-vue"))["Row"]
    ArticleCard: typeof import('./.vitepress/theme/components/feishu/ArticleCard.vue')['default']
    'ArticleCard copy': typeof import('./.vitepress/theme/components/feishu/ArticleCard copy.vue')['default']
    ArticleComment: typeof import('./.vitepress/theme/components/feishu/ArticleComment.vue')['default']
    ArticleCopyright: typeof import('./.vitepress/theme/components/feishu/ArticleCopyright.vue')['default']
    ArticleList: typeof import('./.vitepress/theme/components/feishu/ArticleList.vue')['default']
    'ArticleList copy': typeof import('./.vitepress/theme/components/feishu/ArticleList copy.vue')['default']
    'ArticleList copy 2': typeof import('./.vitepress/theme/components/feishu/ArticleList copy 2.vue')['default']
    ArticleMeta: typeof import('./.vitepress/theme/components/feishu/ArticleMeta.vue')['default']
    ArticleMetadata: typeof import('./.vitepress/theme/components/ArticleMetadata.vue')['default']
    ATag: (typeof import("@arco-design/web-vue"))["Tag"]
    CategoryNav: typeof import('./.vitepress/theme/components/feishu/CategoryNav.vue')['default']
    'CategoryNav copy': typeof import('./.vitepress/theme/components/feishu/CategoryNav copy.vue')['default']
    ChatDialog: typeof import('./.vitepress/theme/components/ChatDialog.vue')['default']
    'ChatDialog copy': typeof import('./.vitepress/theme/components/ChatDialog copy.vue')['default']
    Codeshow: typeof import('./.vitepress/theme/components/codeshow.vue')['default']
    copy: typeof import('./.vitepress/theme/components/Tag copy.vue')['default']
    Feishu: typeof import('./.vitepress/theme/components/feishu.vue')['default']
    FeishuContent: typeof import('./.vitepress/theme/components/feishu/FeishuContent.vue')['default']
    FeishuNav: typeof import('./.vitepress/theme/components/feishu/FeishuNav.vue')['default']
    Home: (typeof import("./.vitepress/theme/components/home.vue"))["default"]
    HomePage: typeof import('./.vitepress/theme/components/unocss/HomePage.vue')['default']
    IconShareAlt: (typeof import("@arco-design/web-vue/es/icon"))["IconShareAlt"]
    IconTrophy: (typeof import("@arco-design/web-vue/es/icon"))["IconTrophy"]
    RainbowAnimationSwitcher: typeof import('./.vitepress/theme/components/unocss/RainbowAnimationSwitcher.vue')['default']
    RainbowSwitcher: typeof import('./.vitepress/theme/components/unocss/RainbowSwitcher.vue')['default']
    SiteFooter: typeof import('./.vitepress/theme/components/site/siteFooter.vue')['default']
    SiteList: typeof import('./.vitepress/theme/components/site/siteList.vue')['default']
    Tag: typeof import('./.vitepress/theme/components/Tag.vue')['default']
    'Tag copy': typeof import('./.vitepress/theme/components/Tag copy.vue')['default']
    WordCloud: typeof import('./.vitepress/theme/components/WordCloud.vue')['default']
  }
}
