name: Deploy To Github Pages

on:
  #允许手动push触发
  repository_dispatch:
    types:
      - deploy

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node-version: [20]

    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install --prod

      - name: 生成静态文件
        env:
          YUQUE_TOKEN: ${{ secrets.YUQUE_TOKEN }}
        run: |
          pnpm run docs:build

      - name: 部署 到Github Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.SSH_PRIVATE_KEY }}
          publish_dir: docs/.vitepress/dist
          external_repository: silvbb/silvbb.github.io
          publish_branch: jxdocs
          commit_message: ${{ github.event.head_commit.message }}
